[package]
name = "makepad-profiler"
version = "0.1.0"
edition = "2024"
description = "Out-of-process sampling profiler for Makepad Studio"
license = "LGPL-3.0"
homepage = "https://github.com/visokit/viso/"
repository = "https://github.com/visokit/viso/"

[dependencies]
makepad-micro-serde = { path = "../../libs/micro_serde", version = "1.0.0" }
