[package]
name = "makepad-wasm-strip"
version = "1.0.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2024"
description = "Makepad shell functions"
license = "LGPL-3.0"
homepage = "https://github.com/visokit/viso/"
repository = "https://github.com/visokit/viso/"
metadata.makepad-auto-version = "m7axzkghrdOa6GR1SQQZ-atSk3s="

[features] 
[dependencies]
