[package]
name = "makepad-cef"
version = "0.1.0"
edition = "2024"
build = "build.rs"
license = "LGPL-3.0"

[dependencies]
libloading = { path = "../vulkan/libloading", version = "0.8.9" }

[target.'cfg(target_os = "macos")'.dependencies]
makepad-objc-sys = { path = "../objc-sys", version = "1.0.0" }
