[package]
name = "makepad-script-derive"
version = "1.0.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2024"
description = "Makepad splash derive macro"
license = "LGPL-3.0"
homepage = "https://github.com/visokit/viso/"
repository = "https://github.com/visokit/viso/"
metadata.makepad-auto-version = "tSPvEgfuhrUzpofjMUEzGZksHSo="

[lib]
proc-macro = true

[dependencies]
makepad-micro-proc-macro = { path = "../../../libs/micro_proc_macro", version = "1.0.0" }

