[package]
name = "makepad-live-id"
version = "1.0.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2024"
description = "Viso live id symbol interning"
license = "LGPL-3.0"
homepage = "https://github.com/visokit/viso/"
repository = "https://github.com/visokit/viso/"
metadata.makepad-auto-version = "Fjf_rJTOgvZXwyU7Yb-CZMF6Hmo="

[dependencies]
makepad-live-id-macros = { path = "id_macros", version = "1.0.0" }
#makepad-error-log = { path = "../error_log", version = "0.4.0" }

serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
default = []
## Enables certain public-facing types to derive serde serialization traits.
serde = ["dep:serde"]
